### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by michaelkrog** [daniel-sc/xliff-simple-merge#16]
I tried to upgrade to latest cliff-simple-merge (from 0.12.4) but it seems like it is unable to finde merge.js.
I tried via `npx xliff-simple-merge` with the same result.

(I trimmed my folders away from the following example)

```
Error: Cannot find module './merge'
Require stack:
- /.../node_modules/xliff-simple-merge/dist/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/.../node_modules/xliff-simple-merge/dist/src/index.js:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/.../node_modules/xliff-simple-merge/dist/src/index.js'
  ]
}
```

**Comment by daniel-sc** [comment]
@michaelkrog did you run the latest version `npx xliff-simple-merge@1.2.0`? What is the exact command (incl. parameters) you used? Which  nodejs version are you using?

**Comment by michaelkrog** [comment]
@daniel-sc 

I am on Mac with Node 18.

```
$ node -v
v18.18.2

$ npx xliff-simple-merge
Need to install the following packages:
xliff-simple-merge@1.2.0
Ok to proceed? (y) 
node:internal/modules/cjs/loader:1080
  throw err;
  ^

Error: Cannot find module './merge'
Require stack:
- /Users/michael/.npm/_npx/e03d4c773e3b6fa8/node_modules/xliff-simple-merge/dist/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/michael/.npm/_npx/e03d4c773e3b6fa8/node_modules/xliff-simple-merge/dist/src/index.js:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/michael/.npm/_npx/e03d4c773e3b6fa8/node_modules/xliff-simple-merge/dist/src/index.js'
  ]
}

Node.js v18.18.2
```

**Comment by michaelkrog** [comment]
Looking at the contents of the release, isn't  merge.js missing?
https://cdn.jsdelivr.net/npm/xliff-simple-merge@1.2.0/dist/src/

**Comment by daniel-sc** [comment]
@michaelkrog Thanks for finding the cause for this. Not sure why this happens, though.. I'll try to cut another release and see if it is correct..

**Comment by daniel-sc** [comment]
@michaelkrog not sure why it ever worked before (maybe depending on OS where release was created..). Please let me know if 1.2.2 does not resolve this!
